# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
    ]
