# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='0', editable=False, max_length=7),
        ),
    ]
